- dreambooth_path: models/DreamBooth_LoRA/rcnzCartoon3d_v10.safetensors
  lora_model_path: ''
  inference_config: configs/inference/inference-v3.yaml
  motion_module: models/Motion_Module/v3_sd15_mm.ckpt
  seed:
  - 8085079222822100088
  - 15493278891844617620
  - 17384760730172253253
  - 3896292336733512420
  steps: 25
  guidance_scale: 8
  prompt:
  - A video of a duckling wearing a medieval soldier helmet and riding a skateboard.
  - A video of a duckling wearing a medieval soldier helmet and riding a skateboard
    in cartoon style.
  - A video of a duckling wearing a medieval soldier helmet and riding a skateboard
    in watercolor style.
  n_prompt:
  - beard, EasyNegative, lowres, chromatic aberration, depth of field, motion blur,
    blurry, bokeh, bad quality, worst quality, multiple arms, badhand
  - beard, EasyNegative, lowres, chromatic aberration, depth of field, motion blur,
    blurry, bokeh, bad quality, worst quality, multiple arms, badhand
  - beard, EasyNegative, lowres, chromatic aberration, depth of field, motion blur,
    blurry, bokeh, bad quality, worst quality, multiple arms, badhand
  W: 512
  H: 512
  L: 16
  random_seed:
  - 8085079222822100088
  - 15493278891844617620
  - 17384760730172253253
