pretrained_model_path: models/stable-diffusion-v1-4
output_dir: ./outputs/test_mine
validation_data:
  prompts:
  - A video of a duckling wearing a medieval soldier helmet and riding a skateboard
    in watercolor style.
  - A video of a duckling wearing a medieval soldier helmet and riding a skateboard
    in watercolor style.
  - A video of a duckling wearing a medieval soldier helmet and riding a skateboard
    in watercolor style.
  - A video of a duckling wearing a medieval soldier helmet and riding a skateboard
    in watercolor style.
  - A video of a duckling wearing a medieval soldier helmet and riding a skateboard
    in watercolor style.
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
  negative_prompt: beard, EasyNegative, lowres, chromatic aberration, depth of field,
    motion blur, blurry, bokeh, bad quality, worst quality, multiple arms, badhand
  interpolate_k: 0
  attention_type_former:
  - self
  - first
  - former
  attention_type_latter:
  - self
  attention_adapt_step: 20
mixed_precision: fp16
enable_xformers_memory_efficient_attention: true
seed: 42
inference_config:
  diversity_rand_ratio: 0.1
