# path:
ckpt_path: "../pretrained_models/lavie_base.pt"
output_folder: "../res/base/watercolor video"
pretrained_path: "../pretrained_models"

# model config: 
model: UNet
video_length: 32
image_size: [320, 512]

# beta schedule
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed: #400
run_time: 0
guidance_scale: 7.5
sample_method: 'ddpm'
num_sampling_steps: 50

text_prompt: [
       "generate a watercolor video depicting the following lyrics Welcome to the forest cave.",
       "generate a watercolor video depicting the following lyrics Beware of the dinosaurs that live here.",
       "generate a watercolor video depicting the following lyrics The scariest animal on earth today.",
       "generate a watercolor video depicting the following lyrics I feel like a Tyrannosaurus will appear out of nowhere.",
       "generate a watercolor video depicting the following lyrics But don't worry.",
       "generate a watercolor video depicting the following lyrics Brachiosaurus will appear and help Tyranno.",
]